### ISSUE TITLE
Proposal: auto-add `hacktoberfest-accepted` label in the last week of October

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-labeler-action#29]

**Comment by kbdharun** [comment]
Hi, thanks for the proposal this would be great from a maintenance perspective, but Hacktoberfest ToS doesn't allow it afaik, see this section:

![Image](https://github.com/user-attachments/assets/d88700d5-7114-43f7-8543-54ddc8b249ac)


```txt
Your PR/MR must be accepted by a maintainer before Hacktoberfest ends on October 31 (in any time zone, UTC-12 thru UTC+14) to be counted.
```
