### ISSUE TITLE
Proposal: add `page edit` for translations as well

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-labeler-action#42]
Right now, `page edit` is only applied to English pages, but why couldn't it be added to translations as well?

**Comment by spageektti** [comment]
That's a good idea, but IMO we should use `translation edit` label instead to make it easier to search for only english page edits.

**Comment by kbdharun** [comment]
> That's a good idea, but IMO we should use `translation edit` label instead to make it easier to search for only english page edits.

Agreed, this would work the best and would also improve filtering.
